Repository Klebert-Engineering/zsr, pull requests merged in 2020-07, with the labels that each got.

#40 Update version to 2.0.0
  .github/workflows/cmake.yml
  extension/src/zserio/emit/cpp_reflect/CppReflectExtensionVersion.java
  runtime/test/zserio/choice_test/choice_test.cpp
  runtime/test/zserio/choice_test/choice_test.zs
  runtime/test/zserio/service_test/service_test.cpp
  runtime/test/zserio/service_test/service_test.zs
  runtime/test/zserio/structure_test/structure_test.cpp
  runtime/test/zserio/structure_test/structure_test.zs
  runtime/test/zserio/union_test/union_test.cpp
  runtime/test/zserio/union_test/union_test.zs
Labels: enhancement :star:

#41 Add msvc flags to add_zserio_module
  runtime/CMakeLists.txt
Labels: bug :bug:

#43 Type check setter values
  runtime/src/field-accessor-helper.hpp
  runtime/src/tmp-helper.hpp
  runtime/test/zserio/structure_test/structure_test.cpp
  runtime/test/zserio/structure_test/structure_test.zs
Labels: bug :bug:

#46 Split zserio packages into sub-package libs (avoid MSVC /bigobj)
  runtime/CMakeLists.txt
  runtime/amalgamate.cmake
  runtime/submodule-depends.py
Labels: bug :bug:, enhancement :star:
