Repository Klebert-Engineering/zsr, pull requests merged in 2020-05, with the labels that each got.

#18 Remove enum CType
  runtime/src/c-type-helper.hpp
  runtime/test/zserio/enumeration_test/enumeration_test.cpp
  runtime/zsr/types.hpp
Labels: bug :bug:

#19 Expose matching parameter field
  runtime/src/reflection-macros.hpp
  runtime/zsr/types.hpp
  runtime/zsr/variant.hpp
Labels: enhancement :star:

#20 Add virtual copy function to introspectable
  runtime/src/introspectable.cpp
  runtime/zsr/introspectable-private.hpp
  runtime/zsr/introspectable.hpp
Labels: enhancement :star:

#21 Expose compounds hash function
  runtime/src/reflection-macros.hpp
  runtime/zsr/types.hpp
Labels: enhancement :star:

#22 Add function for visiting variants
  runtime/zsr/variant.hpp
Labels: enhancement :star:

#24 Support identifier transformation for a more pythonic API
  runtime/src/lib-prefix.cpp
  runtime/src/reflection-macros.hpp
Labels: enhancement :star:

#23 Expose zserio generated bitsize function
  runtime/src/lib-prefix.cpp
  runtime/src/reflection-macros.hpp
  runtime/zsr/types.hpp
Labels: enhancement :star:

#26 Replace global ZSERIO_TLP with function arg
  runtime/CMakeLists.txt
Labels: bug :bug:, enhancement :star:

#27 cmake/Windows: Expose symbols of dynamic libraries.
  runtime/CMakeLists.txt
Labels: bug :bug:

#28 Remove choice cases from ZSR
  extension/src/zserio/emit/cpp_reflect/ReflectionEmitter.java
  runtime/src/reflection-macros.hpp
  runtime/test/zserio/choice_test/choice_test.cpp
  runtime/zsr/find.hpp
  runtime/zsr/types.hpp
Labels: enhancement :star:

#30 Explicitly export symbols
  runtime/CMakeLists.txt
  runtime/zsr/error.hpp
  runtime/zsr/export.hpp
  runtime/zsr/find.hpp
  runtime/zsr/introspectable-private.hpp
  runtime/zsr/introspectable.hpp
  runtime/zsr/stub.hpp
  runtime/zsr/types.hpp
  runtime/zsr/variant.hpp
Labels: enhancement :star:

#31 Emit one compilation-unit per zserio package to reduce link-time
  extension/build.xml
  extension/freemarker/package.cpp.ftl
  extension/freemarker/package.hpp.ftl
  extension/freemarker/reflection-main.cpp.ftl
  extension/freemarker/reflection-traits.hpp.ftl
  extension/src/zserio/emit/cpp_reflect/CppReflectExtension.java
  extension/src/zserio/emit/cpp_reflect/EmitterBase.java
  extension/src/zserio/emit/cpp_reflect/IncludeEmitter.java
  extension/src/zserio/emit/cpp_reflect/LibraryTemplateData.java
  extension/src/zserio/emit/cpp_reflect/PackageTemplateData.java
  extension/src/zserio/emit/cpp_reflect/ReflectionEmitter.java
  extension/src/zserio/emit/cpp_reflect/TraitsEmitter.java
  extension/src/zserio/emit/cpp_reflect/TraitsTemplateData.java
  runtime/CMakeLists.txt
  runtime/src/error.cpp
  runtime/src/field-accessor-helper.hpp
  runtime/src/lib-prefix.cpp
  runtime/src/parameterlist-helper.hpp
  runtime/src/reflection-macros.hpp
  runtime/src/tmp-helper.hpp
  runtime/test/zserio/base.hpp
  runtime/test/zserio/bitmask_test/bitmask_test.cpp
  runtime/test/zserio/enumeration_test/enumeration_test.cpp
  runtime/test/zserio/structure_test/structure_test.cpp
  runtime/zsr/error.hpp
  runtime/zsr/find.hpp
  runtime/zsr/reflection-main.hpp
  runtime/zsr/stub.hpp
  runtime/zsr/types.hpp
Labels: enhancement :star:

#32 Capture typedict by reference
  .github/workflows/cmake.yml
  runtime/src/field-accessor-helper.hpp
  runtime/src/parameterlist-helper.hpp
  runtime/src/reflection-macros.hpp
  runtime/test/zserio/structure_test/structure_test.cpp
  runtime/test/zserio/structure_test/structure_test.zs
Labels: bug :bug:

#33 Emit type information for type-refs
  extension/src/zserio/emit/cpp_reflect/ReflectionEmitter.java
  extension/src/zserio/emit/cpp_reflect/TypeRefVisitor.java
  runtime/test/zserio/structure_test/structure_test.cpp
  runtime/test/zserio/structure_test/structure_test.zs
  runtime/zsr/find.hpp
Labels: bug :bug:
